name: starter_architecture_flutter_firebase
description: A new Flutter project.

publish_to: "none"
version: 2.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  currency_picker: ^2.0.21 # Added currency picker package
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_ui_auth: ^1.16.0
  firebase_ui_firestore: ^1.7.0
  # Add Firebase UI OAuth packages
  firebase_ui_oauth_google: ^1.2.13
  firebase_ui_oauth_apple: ^1.2.13
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  go_router: ^14.6.2
  intl: ^0.19.0 # Ensure this is exactly ^0.19.0 (not ^0.18.0)
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.6.1
  force_update_helper: ^0.1.5
  url_launcher: ^6.3.1
  flutter_sound: ^9.2.13 # Usa la versión más reciente disponible
  path_provider: ^2.1.2 # For temp file storage
  http: ^1.2.0 # For API communication
  permission_handler: ^11.1.0 # To handle microphone permissions
  # Add document scanner packages
  camera: ^0.10.5+9 # Camera plugin
  image_picker: ^1.0.5 # For picking images
  image: ^4.1.3 # For image processing
  flutter_doc_scanner: ^0.0.16
  # Add country code picker
  country_code_picker: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  random_string: ^2.3.1
  flutter_lints: ^5.0.0
  # a tool for running code generators
  build_runner: ^2.4.13
  # the code generator
  riverpod_generator: ^2.6.3
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.6.3
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
